**1) Write a program in python that prints hello world .**

In [158]:
print("hello world")

hello world


**2) Which statement is true? and why?**
1. In Python, a variable must be declared before it is assigned a value 
2. In Python, a variable may be assigned a value of one type, and then later assigned a value of a different type

In [159]:
x = True
y = False
print(x,y)

True False


**3) Consider the following sequence of statements :**\
1.These statements refer to different variables.\
2.These statements refer to the same variable.\
Answer: `Case is significant in Python variable names, so these are all different variables.`

In [160]:
employeenumber = 4398
EmployeeNumber = 4398
employeeNumber = 4398

In [161]:
id(employeenumber)

140509166989424

In [162]:
id(EmployeeNumber)

140509166989488

In [163]:
id(employeeNumber)

140509166989584

**4) Following the execution of these statements, Python has created how many objects and how many references?**\
`1.One object, two references`\
2.One object, one reference\
3.Two objects, one reference\
4.Two objects, two references

In [164]:
n = 300
m = n

In [165]:
id(m)

140509166990416

In [166]:
id(n)

140509166990416

**5) Multiple Variable's Definition**\
Assign values `"pytopia" , 2022 and 3.14` to `var_s , var_i , var_f` in **only one line** of code.

In [167]:
var_s,var_i,var_f = 'pytopia',2022,3.14

In [168]:
var_s

'pytopia'

In [169]:
var_i

2022

In [170]:
var_f

3.14

**6) Variable Assignment**\
Consider the following sequence of statements :

Since numbers between -5 and 256 are used a lot, Python allocates memory for these numbers from the beginning in RAM. For this reason, these objects are made only once and at any time create a variable with these values, instead of making new objects we just create some new pointers to those objects. But for any other numbers any time we create a variable we also create new objects.

Somehow, it can be said that the numbers in this range are unique and occupy the RAM once.

In [171]:
m = 245
n = 245
x = 268
y = 268
z = y

In [172]:
print(id(m),id(n),id(x),id(y),id(z))

140509796206640 140509796206640 140509166991376 140509166991440 140509166991440


In [173]:
id(m) != id(n), id(x) != id(y)

(False, True)

In [174]:
id(m) == id(n), id(x) == id(y)

(True, False)

In [175]:
id(m) == id(n), id(x) != id(y)

(True, True)

In [176]:
id(m) != id(n), id(x) == id(y)

(False, False)

In [177]:
id(z) == id(y)

True

In [178]:
id(z) != id(y)

False

**7) Quick Swap**

Assume we have two variables called input_1 and input_2 . Swap the values of the two variables so that input_1 has the value of input_2 and vice versa. Print out the two variables.  

Note: You must perform the swap in only 1 line of code, and without using any variables other than input_1 and input_2 .

In [179]:
input_1 = 0
input_2 = 1
input_1,input_2 = input_2,input_1

**8) Custom Swap** \
Ali has a problem with one of his python practices.\
He wants `to get two numbers as input from the user` and put them in input_1 and input_2 .\
then Swap the values of the two variables so that input_1 has the value of input_2 and vice versa.\ 
Finally, print out the two variables.

**Note: He must only use 3 variables in his code**

In [180]:
input_1 = int(input("Enter first number: "))
input_2 = int(input("Enter second number: "))

Enter first number: 10
Enter second number: 11


In [181]:
temp = input_1
input_1 = input_2
input_2 = temp

In [182]:
print(input_1,input_2)

11 10


**9) Easy Sum** \
We ask Ali to write a code that takes two inputs from the user and saves them in two desired variables, and then puts the sum of the two inputs in a variable and prints the result. Since Ali does not know the syntax of python, we ask you to help him to write this code!

Note: Use snake case format for variable names.

Hint: You can use the following code to take input from the user and convert it to an integer. (In future sessions we will explain how this code works).

You can change the name of the variable to anything you like.

`Note: When you are giving your input data, press Enter to end the process of giving input after you have done.`


In [183]:
input_1 = int(input('Enter a number: '))
input_2 = int(input('Enter another number: '))

Enter a number: 10
Enter another number: 11


In [184]:
sum_x = input_1 + input_2
print(sum_x)

21


**10) Warm-Up Variable Practice!** \
Ali's programming teacher asks him to define two variables inp_1 and inp_2 and assign values 10 and 35 to them. \
then put inp_1 + inp_2 in variable result and print it. \
Ali is a lazy student and asks you to do this for him!



In [185]:
inp_1,inp_2 = 10,35
sum_inp = inp_1 + inp_2
print(sum_inp)

45


**11) Bitwise Operators Quiz** \
4 is 100 in binary and 11 is 1011. \
What is the output of the following bitwise operators?

4: 0100 \
11: 1011

In [186]:
a = 4
b = 11
print(a | b, a >> 2)

15 1


**12) Operator and Expression** \
What is the output of the following code?

print(bool(0), bool(3.14159), bool(-3), bool(1.0+1j)) 

1. True True False True \
2. False True True True \
3. True True False True \
4. False True False True

`answer: 2`

**13) List Chain Assignment** \
What is the output where indicated by #?:

`Hint: If you think the outputs are [2] and [3], think again!`

The reason is when you do `x = y = []` you define two pointers both pointing to one memory location. \
If you change that memory location with x, the changes are seen by y too, cause both are sharing one memory location.

So be careful when you use chain assignments. It may cause unexpected behaviours when used with mutable data types.

Note that with immutable variables, there is no problem like this, cause they are not gonna change.

In [187]:
x = y = []
x.append(2)
y.append(3)
print(x)
print(y)

[2, 3]
[2, 3]


**14) Append to The List** \
The append() method allows you to add items to your lists. \
Add the string "R" to the programming_langs list with append() method.

Note: Python's list contents are references unless documented otherwise, no copies are created when you pass a name to a method. This applies just as much to list.append() as to any other call; list.append() adds a reference to the list, not a copy.

In [188]:
programming_langs = ["Julia", "Python"] 
programming_langs.append("R")

In [189]:
programming_langs

['Julia', 'Python', 'R']

**15) List: Max, Min, Sum and Mean** \
Calculate the maximum, minimum, sum and mean of the following data using python's built-in functions:



In [190]:
random_num_data = [18, 60, -10, 17, 55, 8, -1, 31, 52, 31,
                    27, 14, 25, 0, -2, 15, -1, 50, 45, -4,
                    42, -10, 40, 3, 43, 55, 24, -17, 17, 54, 
                    19, 24, 44, 30, 24, 3, -17, 31, 45, -10, 
                    13, -12, 21, -13, 52, 57, -1, 37, 21, 42]

In [191]:
maximum = max(random_num_data)
maximum

60

In [192]:
minimum = min(random_num_data)
minimum

-17

In [193]:
sum_of_data = sum(random_num_data)
sum_of_data

1091

In [194]:
mean_of_data = sum(random_num_data) / len(random_num_data)
mean_of_data

21.82

**16) Second Largest Number In List** \
Find the second_largest number in the list:

`second_largest = 66`

In [195]:
num_list = [3, 47, 10, 15, 21, 28, 13, 45, 66, 12, 34, 56, 78]
num_list

[3, 47, 10, 15, 21, 28, 13, 45, 66, 12, 34, 56, 78]

In [196]:
# method 1
max(num_list)

78

In [197]:
num_list.remove(78)

In [198]:
max(num_list)

66

In [199]:
# method 2
sorted_list = sorted(num_list)
sorted_list

[3, 10, 12, 13, 15, 21, 28, 34, 45, 47, 56, 66]

In [200]:
second_largest = sorted_list[-2]
second_largest

56

**17) List Quiz** \
Which of the following are `not true` about Python lists? (Choose all that may apply)

1. There is no limit to the size of a list.
2. All elements in a list must be of the same type.
3. A list may contain any type of object except another list
4. A given object may appear in a list more than once.

`answer: Choice 2, is not True. This statement is not relevant to the list data type in python. what it's referring though, is an array.
Choice 3, is not True. Alist can contain any object, including another list (nested list).`

**18) Nested List Indexing** \
Extract the fourth team list from persian_gulf_standing:

In [201]:
persian_gulf_standing = [
    ['Esteghlel F.C', 1],
    ['Sepahan', 2],
    ['Perspolis', 3],
    ['Gol Gohar', 4],
    ['Foolad', 5]
]

# forth_team = #Code here

In [202]:
# method 1
persian_gulf_standing[3][0]

'Gol Gohar'

In [203]:
# method 2
forth_team = persian_gulf_standing[:][-2] 
forth_team

['Gol Gohar', 4]

**19) List Subset** \
Subset the following lists from color list:

In [204]:
bl_gr = ['blue', 'green']
re_gr_br = ['red', 'green', 'brown']
pk_br_yl = ['pink', 'brown', 'yellow']

In [205]:
colors = ['red', 'blue', 'green', 'yellow', 'brown', 'pink']

#### bl_gr = #?

In [206]:
bl_gr = colors[1:3]
bl_gr

['blue', 'green']

#### re_gr_br = #?

In [207]:
# method 1
re_gr_br = colors[0:5:2]
re_gr_br

['red', 'green', 'brown']

In [208]:
# method 2
re_gr_br = colors[::2]
re_gr_br

['red', 'green', 'brown']

#### pk_br_yl = #?

In [209]:
# method 1
pk_br_yl = colors[3:]
pk_br_yl

['yellow', 'brown', 'pink']

In [210]:
pk_br_yl = colors[-1:-4:-1]
pk_br_yl

['pink', 'brown', 'yellow']

**20) List Memory Usage** \
Consider the following line of code :

a = 300 , b = 124 , mylist = [300, 124, 100]

`Answer: 124 is between -5 and 256 and as you know python reserves memory for these numbers and these objects are created only once. So when you have a list with value 124 in it, it doesn't create a new object, Only a pointer point to the address as variable a point. so they have same id But for 300 it creates an object and b points to it. then when you create a list that has a value of 300 in it, it creates a new object with value 300 and it has the list's pointer. so the list pointer and variable b do not point to the same object and they have a different id.`

In [211]:
mylist = [300, 124, 100]
a,b = 300,124

In [212]:
print(id(a),id(b),id(mylist[1]))

140509165693328 140509796202704 140509796202704


In [213]:
id(a) == id(mylist[0]) and id(b) == id(mylist[1])

False

In [214]:
id(a) == id(mylist[0]) and id(b) != id(mylist[1])

False

In [215]:
id(a) != id(mylist[0]) and id(b) == id(mylist[1])

True

In [216]:
id(a) != id(mylist[0]) and id(b) != id(mylist[1])

False

In [217]:
id(a) == id(mylist) and id(b) == id(mylist)

False

**21) Delete List items**

What is the output of the following code?

`answer : []
When your index is greater than the number of items in the list, del won't give an error. it removes all elements of the list. it means that it read indexes until the end of your list and then terminates.`

In [218]:
inp_list = [10, 20, 30, 40]
del inp_list[0:6]
print(inp_list)

[]


**22) Replace List Items with New Values** \
Ali put his student's math grades on a list. One of the students has been suspended with a score of 9.75. Today is Ali's birthday and he wants to give 10 to that student. we want you to find the value 9.75 in the given list, and replace it with 10. Only update the first occurrence of the item.

In [219]:
grades = [12, 19, 14, 15, 17.5, 18, 10.25, 9.75, 19, 14, 12, 11.25, 17, 18, 13, 13, 15, 19, 18.5]

In [220]:
print(grades)

[12, 19, 14, 15, 17.5, 18, 10.25, 9.75, 19, 14, 12, 11.25, 17, 18, 13, 13, 15, 19, 18.5]


In [221]:
# method 1
grades_sorted = sorted(grades)
print(grades_sorted)

[9.75, 10.25, 11.25, 12, 12, 13, 13, 14, 14, 15, 15, 17, 17.5, 18, 18, 18.5, 19, 19, 19]


In [222]:
grades_sorted[0] = 10

In [223]:
print(grades_sorted)

[10, 10.25, 11.25, 12, 12, 13, 13, 14, 14, 15, 15, 17, 17.5, 18, 18, 18.5, 19, 19, 19]


In [224]:
# method 2

# get the first occurrence index
index = grades.index(9.75)

# update item present at location
grades[index] = 10
print(grades)

[12, 19, 14, 15, 17.5, 18, 10.25, 10, 19, 14, 12, 11.25, 17, 18, 13, 13, 15, 19, 18.5]


**23) Simple List Indexing** \
Use indexes and print the first, third, and last element of the list below. \
Note: #? is just a comment indicating where you should write your code.

In [225]:
num_list = [1, 3, 6, 10, 15, 21, 28, 36, 45, 55, 66, 78]
# first_element = #? third_element = #? last_element =  #?

In [226]:
first_element = num_list[0]
first_element

1

In [227]:
third_element = num_list[2]
third_element

6

In [228]:
last_element = num_list[-1]
last_element

78

**24) Tuple: Remove an Item** \
Write a Python program to remove item `"hafez"` from a tuple and save it in persian_poets_wo_hafez

`Answer: Tuples are immutable, so you can not remove elements.`

In [229]:
persian_poets = ('saadi', 'frough', 'hafez', 'parvin', 'saeb')

In [230]:
type(persian_poets)

tuple

In [231]:
# method 1
## Using the merge of tuples with the + operator, you can remove an item, and it will create a new tuple.
persian_poets_wo_hafez  = persian_poets[:2] + persian_poets[3:]
persian_poets_wo_hafez

('saadi', 'frough', 'parvin', 'saeb')

In [232]:
# method 2
## first convert tuple to list
persian_poets = list(persian_poets)

In [233]:
persian_poets

['saadi', 'frough', 'hafez', 'parvin', 'saeb']

In [234]:
# use different ways to remove an item of the list
persian_poets.remove('hafez')

In [235]:
persian_poets

['saadi', 'frough', 'parvin', 'saeb']

In [236]:
# converting the tuple to list
persian_poets_wo_hafez = tuple(persian_poets)
persian_poets_wo_hafez

('saadi', 'frough', 'parvin', 'saeb')

**25) Simple Tuple Indexing 2** \
Copy specific elements from one tuple to a new tuple\
Write a program to copy elements 44 and 55 from the following tuple into a new tuple. tuple2 = (44, 55)

In [237]:
tuple1 = (11, 22, 33, 44, 55, 66)

In [238]:
# method 1
tuple2 = tuple1[3:5]
tuple2

(44, 55)

In [239]:
# method 2
tuple2 = tuple1[3:-1]
print(tuple2)

(44, 55)


**26) Unpack Tuple** \
Unpack the tuple into 4 variables.\
Write a program to unpack the following tuple into four variables: sohrab faramarz jahangir siyavash

In [240]:
shahnameh_tuple = ('Sohrab', 'Faramarz', 'Jahangir', 'Siyavash')
#write your code here

In [241]:
sohrab,faramarz,jahangir,siyavash = shahnameh_tuple

In [242]:
sohrab

'Sohrab'

In [243]:
faramarz

'Faramarz'

In [244]:
jahangir

'Jahangir'

In [245]:
siyavash

'Siyavash'

**27) Reverse Tuple** \
Reverse the following tuple and save it in reverse_num_tup :

In [246]:
num_tup = (10, 20, 30, 40, 50)
# reverse_num_tup = #?

In [247]:
reverse_num_tup = num_tup[::-1]
reverse_num_tup

(50, 40, 30, 20, 10)

**28) Simple Tuple Indexing** \
For the `mixed_tuple` variable defined below:
1) Access value 20 from the mixed_tuple
2) Access the charachter "g" from the mixed_tuple 
3) The given tuple is a nested one. Write a Python program that prints the value 20 with indexing.

In [248]:
mixed_tuple = ("Orange", [10, 20, 30], (5, 15, 25))

In [249]:
# answer 1
mixed_tuple[1][1]

20

In [250]:
# answer 2
# method 1
mixed_tuple[0][4]

'g'

In [251]:
# answer 2
# method 2
mixed_tuple[0][-2]

'g'

In [252]:
# answer 3
mixed_tuple.index([10,20,30])

1

**29) Building a Dictionary Incrementally** \
First use `{}` to create an empty dictionary named bmw, then add a `"red"` value to the bmw dictionary for the `"color"` key.

In [253]:
bmw = {}

In [254]:
# method 1
bmw = {'color':'red'}

In [255]:
bmw

{'color': 'red'}

In [256]:
# method 2
bmw['color'] = 'red'

In [257]:
bmw

{'color': 'red'}

**30) Restrictions on Dictionary Keys and Values** \
Which of the following options defines a dictionary incorrectly: \
(Set the variable `q9_answer` to the option number you choose to answer this question)

1. foo = {1: 'aaaa', 3.14: 'bbbb', 6.18: 'ccc'}
2. foo = {[1, 3.14]: 'a', [2, 6.28]: 'b'}
3. foo = {(1, 3.14): 'a', (2, 12.56): 'b'}
4. foo = {dict: [], float: 2, int: 3.14}

`q9_answer = 2`

**31) Dictionary get() method 1** \
You can access the value of the dictionaty using `.get()` method:

syntax:\
`dictionary.get(keyname)`

for example:


In [258]:
rostam_data = {
    "name": "Rostam",
    "nationality": "Turanian",
    "father": "Zal" ,
    "mother": "Rudaabeh",
    "spouse": "Tahmineh",
    "grandfather": "Sam",
    "delivery": "C-Section",
    "POB": "Zabol",
    "POD" : "Kabul"
    }
rostam_data.get('father')

'Zal'

According to the `Shahnameh`, the Simurgh instructed `Zal` upon how to perform a caesarean section, thus saving `Rudaba and the child Rostam`. In Persian literature ceaserean section is known as Rostamina.
Please **print the type of birth** (delivery) of Rostam using the `get()` method

In [259]:
print(rostam_data.get('delivery'))

C-Section


**32) Dictionary get() method 2** \
The .get() method allows us to retrieve the value of the wanted key from the dictionary while also preventing an error if the key is not found in the dictionary. and receive the previously set default value. For example, suppose we have a dictionary of students and their math score

```python
math = {
    'abtin': 19,
    'laleh': 20,
    'mehri': 18,
    }

```

If we do not know exactly which students are in the dictionary and, for example, if we want to read Kamran's math grade, then we will encounter an error.

In [260]:
math = {
    'abtin': 19,
    'laleh': 20,
    'mehri': 18,
    }

In [261]:
# math['kamran']

In [262]:
math.get('kamran')

We can add a value to the `.get()` method to return that value if the requested key does not exist.
syntax:

In [263]:
# dictionary.get(keyname, <value>)

A to return if the specified key does not exist. Default value is None

In [264]:
math.get('kamran', 666)

666

In [265]:
math.get('laleh',666)

20

The following dictionary is based on the book Shahnameh by Abolghasem Ferdowsi, a famous Iranian poet:

In [266]:
rostam_data = {
    "name": "Rostam",
    "nationality": "Turanian",
    "father": "Zal" ,
    "mother": "Rudaabeh",
    "spouse": "Tahmineh",
    "grandfather": "Sam",
    "delivery": "C-Section",
    "POB": "Zabol",
    "POD" : "Kabul"
    }

In [267]:
rostam_data

{'name': 'Rostam',
 'nationality': 'Turanian',
 'father': 'Zal',
 'mother': 'Rudaabeh',
 'spouse': 'Tahmineh',
 'grandfather': 'Sam',
 'delivery': 'C-Section',
 'POB': 'Zabol',
 'POD': 'Kabul'}

Because Rostam's `"date of birth"` might **not be in our dictionary**, use one of the `.get()` methods to print Rostam's date of birth and ensure that if Rostam's date of birth does not exist, the number `-87` is printed and no error occurs.

In [268]:
print(rostam_data.get("data of birth", -87))

-87


**33) Accessing Dictionary Values 1** \
The following dictionary is based on the book **Shahnameh** by **Abolghasem Ferdowsi,** a famous Iranian poet.
According to the dictionary below, print the name of Rostam's mother and wife using a single print() function.

In [269]:
rostam_data = {
    "name": "Rostam",
    "nationality": "Turanian",
    "father": "Zal" ,
    "mother": "Rudaabeh",
    "spouse": "Tahmineh",
    "grandfather": "Sam",
    "delivery": "C-Section",
    "POB": "Zabol",
    "POD" : "Kabul"
    }

In [270]:
rostam_data

{'name': 'Rostam',
 'nationality': 'Turanian',
 'father': 'Zal',
 'mother': 'Rudaabeh',
 'spouse': 'Tahmineh',
 'grandfather': 'Sam',
 'delivery': 'C-Section',
 'POB': 'Zabol',
 'POD': 'Kabul'}

In [271]:
# print the name of Rostam's mother and wife using a single print() function.
print(f"the name of Rostams mother's and wife is {rostam_data['mother'],rostam_data['spouse']}")

the name of Rostams mother's and wife is ('Rudaabeh', 'Tahmineh')


In [272]:
print(f"mother's name: {rostam_data['mother']}, rostam's wife:{rostam_data['spouse']}")

mother's name: Rudaabeh, rostam's wife:Tahmineh


**34) Accessing Dictionary Values 2** \
The following dictionary is based on the book **Shahnameh** by **Abolghasem Ferdowsi**, a famous Iranian poet.
**Rostam** nationality has been registered as a **Turanian**. Please change **Rostam** nationality to **Iranian.**

In [273]:
rostam_data = {
    "name": "Rostam",
    "nationality": "Turanian",
    "father": "Zal" ,
    "mother": "Rudaabeh",
    "spouse": "Tahmineh",
    "grandfather": "Sam",
    "delivery": "C-Section",
    "POB": "Zabol",
    "POD" : "Kabul"
    }

In [274]:
rostam_data

{'name': 'Rostam',
 'nationality': 'Turanian',
 'father': 'Zal',
 'mother': 'Rudaabeh',
 'spouse': 'Tahmineh',
 'grandfather': 'Sam',
 'delivery': 'C-Section',
 'POB': 'Zabol',
 'POD': 'Kabul'}

In [275]:
rostam_data['nationality'] = 'Iranian'

In [276]:
rostam_data

{'name': 'Rostam',
 'nationality': 'Iranian',
 'father': 'Zal',
 'mother': 'Rudaabeh',
 'spouse': 'Tahmineh',
 'grandfather': 'Sam',
 'delivery': 'C-Section',
 'POB': 'Zabol',
 'POD': 'Kabul'}

**35) Accessing Dictionary Values 3** \
The following dictionary is based on the book **Shahnameh** by **Abolghasem Ferdowsi,** a famous Iranian poet.
Rostam's children were **Sohrab, Faramarz, Jahangir, Siyavash,** and **Banu-Goshasp.** Please add a list of Rostam's children's names with the key childrens to rostam_data dictionary.

In [277]:
rostam_data = {
    "name": "Rostam",
    "nationality": "Turanian",
    "father": "Zal" ,
    "mother": "Rudaabeh",
    "spouse": "Tahmineh",
    "grandfather": "Sam",
    "delivery": "C-Section",
    "POB": "Zabol",
    "POD" : "Kabul"
    }

In [278]:
rostam_data["Rostam's children"] = ["Sohrab", "Faramarz", "Jahangir", "Siyavash","Banu-Goshasp"]

In [279]:
rostam_data

{'name': 'Rostam',
 'nationality': 'Turanian',
 'father': 'Zal',
 'mother': 'Rudaabeh',
 'spouse': 'Tahmineh',
 'grandfather': 'Sam',
 'delivery': 'C-Section',
 'POB': 'Zabol',
 'POD': 'Kabul',
 "Rostam's children": ['Sohrab',
  'Faramarz',
  'Jahangir',
  'Siyavash',
  'Banu-Goshasp']}

**36) Convert a list to a dictionary** \
You can also construct a dictionary with the built-in `dict()` function. The argument to `dict()` should be a sequence of key-value pairs.
We have a list called `persian_gulf_standing` that contains pairs, the name of the football team and its position in the `Iranian Football Premier League` (Persian Gulf). We ask you to convert the following list into a dictionary with the same name based on the description provided.

In [280]:
persian_gulf_standing = [
    ['Esteghlel F.C', 1],
    ['Sepahan', 2],
    ['Perspolis', 3],
    ['Gol Gohar', 4],
    ['Foolad', 5]
]

In [281]:
type(persian_gulf_standing)

list

In [282]:
persian_gulf_standing = dict(persian_gulf_standing)

In [283]:
type(persian_gulf_standing)

dict

**37) Arash site users** \
Arash has a list of site users and wants to save them using one of the Python data structures. Initially, he intended to create a list of his users. However, we explained to him that while adding and deleting items at the end of the list is quick, doing so at the beginning of the list is slow because all of the other items must be shifted. Finally, we advised him to use a dictionary because hashes allow him to access all data in a short period of time.

Arash users information is available below:

id	name	family \
1	Kourosh	Kouroshi \
2	Shirin	Shirini \


Please help him put them in a dictionary called `arash_users.` In such a way that it has access to the information of its users via `id.` for example:

In [284]:
arash_users = [["Kourosh","Kouroshi"],["Shirin","Shirini"]]

In [285]:
arash_users

[['Kourosh', 'Kouroshi'], ['Shirin', 'Shirini']]

In [286]:
type(arash_users)

list

In [287]:
arash_users = dict(arash_users)

In [288]:
arash_users['Shirin']

'Shirini'

In [289]:
arash_users = {
    1: {'name': 'Kourosh','family':'Kouroshi'},
    2: {'name': 'Shirin','family':'shirini'},
}

In [290]:
arash_users

{1: {'name': 'Kourosh', 'family': 'Kouroshi'},
 2: {'name': 'Shirin', 'family': 'shirini'}}

In [291]:
arash_users[1]['name']

'Kourosh'

**38) A deeper look at the dictionary**

Which of the following **does not describe** a dictionary? \
(Set the variable `q1_answer` to the option number you choose to answer this question.)

1) Dictionary is mutable.
2) Dictionary is dynamic. It can grow and shrink as needed.
3) Dictionary can be nested. A dictionary can contain another dictionary. A dictionary can also contain a list, and vice versa.
4) Dictionary elements are accessed by their position in the dictionary, via `indexing`

`answer: 4`

**39) Set operations**

- Make a set of **multiples of 3** and name it <font color=red>**X**</font>.

In [1]:
X = {1,3,6,9,12,15}

In [2]:
X

{1, 3, 6, 9, 12, 15}

- Make a set of **multiples of 5** and name it <font color=red>**Y**</font>.

In [10]:
Y = {1,5,10,15,20,25}

In [11]:
Y

{1, 5, 10, 15, 20, 25}

- Can you find the **multiples of 15** using the <font color=red>**&**</font> operator and store it in variable <font color=red>**Z1**</font>?

In [19]:
Z1 = X & Y
Z1

{1, 15}

- Can you find the **multiples of 15** using the <font color=red>**intersection()**</font> method and store it in variable <font color=red>**Z2**</font>?


In [17]:
Z2 = X.intersection(Y)
Z2

{1, 15}

- Then find the multiples of 5 that are not divisible by 3. (hint: use the operator - or use the <font color=red>**difference()**</font> method)


In [21]:
Y-X

{5, 10, 20, 25}

In [22]:
Y.difference(X)

{5, 10, 20, 25}

- after that use the <font color=red>**+**</font> operators or the <font color=red>**union()**</font> method to make a list of numbers that are either divisible by 5 **or** divisible by 3, **or** divisible by both.

In [24]:
X.union(Y)

{1, 3, 5, 6, 9, 10, 12, 15, 20, 25}

**40) Add an element to the set**

Oops! apparently one of the prime numbers below One thousand, 997, is missing. Can you add it to <font color=red>**primes**</font> vaiable? Then check to see if 997 is in primes variable.

In [26]:
primes = {2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41,
          43, 47, 53, 59, 61, 67, 71, 73, 79, 83, 89, 97,
          101, 103, 107, 109, 113, 127, 131, 137, 139, 149,
          151, 157, 163, 167, 173, 179, 181, 191, 193, 197,
          199, 211, 223, 227, 229, 233, 239, 241, 251, 257,
          263, 269, 271, 277, 281, 283, 293, 307, 311, 313,
          317, 331, 337, 347, 349, 353, 359, 367, 373, 379,
          383, 389, 397, 401, 409, 419, 421, 431, 433, 439,
          443, 449, 457, 461, 463, 467, 479, 487, 491, 499,
          503, 509, 521, 523, 541, 547, 557, 563, 569, 571,
          577, 587, 593, 599, 601, 607, 613, 617, 619, 631,
          641, 643, 647, 653, 659, 661, 673, 677, 683, 691,
          701, 709, 719, 727, 733, 739, 743, 751, 757, 761,
          769, 773, 787, 797, 809, 811, 821, 823, 827, 829,
          839, 853, 857, 859, 863, 877, 881, 883, 887, 907,
          911, 919, 929, 937, 941, 947, 953, 967, 971, 977,
          983, 991}

In [28]:
print(primes)

{2, 3, 5, 7, 521, 11, 523, 13, 17, 19, 23, 541, 29, 31, 547, 37, 41, 43, 557, 47, 563, 53, 569, 59, 571, 61, 577, 67, 71, 73, 587, 79, 593, 83, 599, 89, 601, 607, 97, 101, 613, 103, 617, 107, 619, 109, 113, 631, 127, 641, 131, 643, 647, 137, 139, 653, 659, 149, 661, 151, 157, 673, 163, 677, 167, 683, 173, 179, 691, 181, 701, 191, 193, 197, 709, 199, 719, 211, 727, 733, 223, 227, 739, 229, 743, 233, 239, 751, 241, 757, 761, 251, 257, 769, 773, 263, 269, 271, 787, 277, 281, 283, 797, 293, 809, 811, 307, 821, 311, 823, 313, 827, 317, 829, 839, 331, 337, 853, 857, 347, 859, 349, 863, 353, 359, 877, 367, 881, 883, 373, 887, 379, 383, 389, 907, 397, 911, 401, 919, 409, 929, 419, 421, 937, 941, 431, 433, 947, 439, 953, 443, 449, 967, 457, 971, 461, 463, 977, 467, 983, 479, 991, 487, 491, 499, 503, 509}


In [29]:
primes.add(997)

In [30]:
print(primes)

{2, 3, 5, 7, 521, 11, 523, 13, 17, 19, 23, 541, 29, 31, 547, 37, 41, 43, 557, 47, 563, 53, 569, 59, 571, 61, 577, 67, 71, 73, 587, 79, 593, 83, 599, 89, 601, 607, 97, 101, 613, 103, 617, 107, 619, 109, 113, 631, 127, 641, 131, 643, 647, 137, 139, 653, 659, 149, 661, 151, 157, 673, 163, 677, 167, 683, 173, 179, 691, 181, 701, 191, 193, 197, 709, 199, 719, 211, 727, 733, 223, 227, 739, 229, 743, 233, 239, 751, 241, 757, 761, 251, 257, 769, 773, 263, 269, 271, 787, 277, 281, 283, 797, 293, 809, 811, 307, 821, 311, 823, 313, 827, 317, 829, 839, 331, 337, 853, 857, 347, 859, 349, 863, 353, 359, 877, 367, 881, 883, 373, 887, 379, 383, 389, 907, 397, 911, 401, 919, 409, 929, 419, 421, 937, 941, 431, 433, 947, 439, 953, 443, 449, 967, 457, 971, 461, 463, 977, 467, 983, 479, 991, 997, 487, 491, 499, 503, 509}


In [31]:
997 in primes

True

**41) A list or a set, ay there's the point**

The following is a set of prime numbers **less than 1000.** Can you check to see if the numbers **463, 149,** and **973** are prime? **Which is better for determining the presence or absence of an item in a group of items, a list or a set?**

`answer: set`

In [32]:
primes = {2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41,
          43, 47, 53, 59, 61, 67, 71, 73, 79, 83, 89, 97,
          101, 103, 107, 109, 113, 127, 131, 137, 139, 149,
          151, 157, 163, 167, 173, 179, 181, 191, 193, 197,
          199, 211, 223, 227, 229, 233, 239, 241, 251, 257,
          263, 269, 271, 277, 281, 283, 293, 307, 311, 313,
          317, 331, 337, 347, 349, 353, 359, 367, 373, 379,
          383, 389, 397, 401, 409, 419, 421, 431, 433, 439,
          443, 449, 457, 461, 463, 467, 479, 487, 491, 499,
          503, 509, 521, 523, 541, 547, 557, 563, 569, 571,
          577, 587, 593, 599, 601, 607, 613, 617, 619, 631,
          641, 643, 647, 653, 659, 661, 673, 677, 683, 691,
          701, 709, 719, 727, 733, 739, 743, 751, 757, 761,
          769, 773, 787, 797, 809, 811, 821, 823, 827, 829,
          839, 853, 857, 859, 863, 877, 881, 883, 887, 907,
          911, 919, 929, 937, 941, 947, 953, 967, 971, 977,
          983, 991}
check_13 = 13 in primes
print("13 is prime: ",check_13)

13 is prime:  True


In [46]:
check_463 = 463 in primes
check_149 = 149 in primes
check_973 = 973 in primes

In [48]:
print(check_149,check_463,check_973)

True True False


**42) One-digit prime numbers**

Create a Set of one-digit prime numbers and store it in the primes variable and print it.

In [52]:
primes = {2,3,5,7}

In [53]:
print(primes)

{2, 3, 5, 7}
